apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-store
  labels:
    app: netprobe
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi