apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netprobe-role
  labels:
    app: netprobe
    chart: netprobe-1.0.0
    release: netprobe
    heritage: Helm
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]