apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netprobe-daemonset
spec:
  template:
    spec:
      containers:
      - name: netprobe
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netprobe-statefulset
spec:
  template:
    spec:
      containers:
      - name: netprobe
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      - name: collection-agent
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"