apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netprobe-daemonset
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7036"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netprobe-statefulset
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7036"