apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netprobe-daemonset
spec:
  template:
    spec:
      containers:
      - name: netprobe
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netprobe-statefulset
spec:
  template:
    spec:
      containers:
      - name: netprobe
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      - name: collection-agent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000